include:
  - project: 'dev/platform/gitlab-templates'
    ref: main
    file: '/gitlab-ci/includes/deploy.gitlab-ci.yml'

stages:
  - lint
  - build
  - deploy

variables:
  namespace: tools-deanon-${CI_ENVIRONMENT_SLUG}

Lint:
  stage: lint
  image: $GCP_REGISTRY_URL/werf:ci-nodejs-latest
  script:
    - echo "//gitlab.superdao.co/:_authToken=${NPM_TOKEN}" >> .npmrc
    - pnpm config set store-dir .pnpm-store
    - pnpm install --prefer-offline
    - pnpm run lint:ci
  cache:
    - key:
        files:
          - pnpm-lock.yaml
      paths:
        - .pnpm-store
    - key: eslint
      paths:
        - ./{apps,packages}/*/.eslintcache

Build:
  stage: build
  extends: .base_build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Deploy to prod:
  extends: .base_deploy
  environment:
    name: prod
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
